import { Box } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import { Icon } from "../src/components/atoms";
import { generateSxStyles, theme } from "../styles/theme.config";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Wedding of Ririn Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={styles.container}>
        <Box sx={styles.hero}>
          <Box sx={styles.heroAwan}>
            <Icon.Awan />
          </Box>
          <Box sx={styles.heroSiluet}>
            <Icon.GedungSiluet />
          </Box>
          <Box sx={styles.heroAspal}>
            <Icon.Aspal />
          </Box>
          <Box sx={styles.heroPlane}>
            <Icon.Plane />
          </Box>
          <Box sx={styles.heroCharacter}>
            <Icon.Character />
          </Box>
        </Box>
      </Box>
    </>
  );
};

export default Home;

//#region STYLES
const styles = generateSxStyles({
  container: {
    backgroundColor: theme.colors?.background,
    minHeight: "100vh",
    maxWidth: 1280,
    overflow: "hidden",
    margin: "auto",
  },
  hero: {
    position: "relative",
    height: "100vh",
    width: "100%",
    justifyContent: "center",
    display: "flex",
    overflow: "hidden",
  },
  heroAspal: {
    position: "absolute",
    bottom: 0,
    backgroundColor: theme.colors?.aspal,
    display: "flex",
    justifyContent: "center",
  },
  heroSiluet: {
    position: "absolute",
    bottom: 130,
    display: "flex",
    justifyContent: "center",
  },
  heroCharacter: {
    position: "absolute",
    display: "flex",
    justifyContent: "flex-end",
    width: "100%",
    maxWidth: 1024,
    bottom: -50,
  },
  heroPlane: {
    position: "absolute",
    display: "flex",
    justifyContent: "center",
    bottom: 100,
  },
  heroAwan: {
    position: "absolute",
    display: "flex",
    justifyContent: "center",
    bottom: 100,
  },
});
//#endregion
